#!/bin/bash

# ------------------- Compile Maven Project -------------------- #

#changes directory to glide-template and runs mvn clean verify

CWD=`pwd`

# Get the path of the files which are getting modified
# need to write code

# Move to the project directory which you want to compile

mvn test-compile
if [ $? -ne 0 ]; then
  cd $CWD
  echo 'Git Push [ABORTED] >-----------> because of existing issues, Please check logs!'
  exit 1
else
    echo 'Compilation Status: No issues found >--------------------------> [SUCCESSFUL]'
    echo 'Git Push >-----------------------------------------------------> [SUCCESSFUL]'
fi
cd $CWD
