#!/bin/bash

#changes directory to glide-template and runs mvn clean verify

CWD=`pwd`
# Move to the project directory which you want to build
# cd glide-template
mvn clean verify -Dmaven.test.skip=true
if [ $? -ne 0 ]; then
  cd $CWD
  exit 1
fi
cd $CWD
