#!/bin/bash

#Prepends commit message with STRY, DEF, BAK tickets or MAINT

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ $CURRENT_BRANCH == "HEAD" ]
then
    echo 'current branch == HEAD'
    exit 0;
fi

PREFIX_REGEX="((DEF|BAK|STRY|MAINT|def|bak|stry|maint)[0-9]*)"
if [[ $CURRENT_BRANCH =~ $PREFIX_REGEX ]]
then
    TICKET="${BASH_REMATCH[0]}"
    COMMIT_MESSAGE=$(cat $COMMIT_MSG_FILE)
    
    if [[ $COMMIT_MESSAGE =~ $TICKET ]]
    then
        exit 0;
    fi

    echo "Ticket '${TICKET}', matched in current branch name, prepended to commit message."
    echo "New Commit Message >>>> TEST: ${TICKET}: ${COMMIT_MESSAGE}" > $COMMIT_MSG_FILE
fi