#!/bin/bash

#Append commit message with STRY, DEF, BAK tickets or MAINT

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
# echo "CURRENT_BRANCH = "${CURRENT_BRANCH}
PREFIX_REGEX="((DEF|BAK|STRY|MAINT|def|bak|stry|maint|TNTC)[0-9]*)"
PREFIX_REGEX_UNDERSCORE="((DEF|BAK|STRY|MAINT|def|bak|stry|maint|TNTC)[0-9]*)(_*).*"
PREFIX_REGEX_HYPHEN="((DEF|BAK|STRY|MAINT|def|bak|stry|maint|TNTC)[0-9]*)(-*).*"

separator=""
if [[ $CURRENT_BRANCH == "$PREFIX_REGEX"* ]]
then
    if [[ $CURRENT_BRANCH == "$PREFIX_REGEX_UNDERSCORE"* ]]
    then
        #echo "branch name cotains underscore"
        separator="_"
    elif [[ $CURRENT_BRANCH == "$PREFIX_REGEX_HYPHEN"* ]]
    then
        #echo "branch name cotains hyphen"
        separator="-"
    fi
    arr=(${CURRENT_BRANCH//${separator}/ })
    # Modify the current branch value as only the workitem (def/stry/tntc) number
    CURRENT_BRANCH=${arr[0]}
fi

# echo "CURRENT_BRANCH = "${CURRENT_BRANCH} #

# PREFIX_REGEX="((DEF|BAK|STRY|MAINT|def|bak|stry|maint|TNTC)[0-9]*)(_*).*"

COMMIT_MESSAGE=$(cat $COMMIT_MSG_FILE)
MIN_COMMIT_LENGTH=5
COMMIT_MESSAGE_LENGTH=$(echo -n "$COMMIT_MESSAGE" | wc -c)

if [[ $COMMIT_MESSAGE_LENGTH -lt $MIN_COMMIT_LENGTH ]]
then
    echo 'COMMIT_MESSAGE_LENGTH = '$COMMIT_MESSAGE_LENGTH
    echo 'MIN_COMMIT_LENGTH = '$MIN_COMMIT_LENGTH
    echo 'Commit message is too short..... Commit --------------------------> [ABORTED]'
    exit 1;
fi

if [[ $CURRENT_BRANCH =~ $PREFIX_REGEX ]]
then
    TICKET="${BASH_REMATCH[0]}"
    # echo "TICKET IS = "${TICKET}
    
    if [[ ! $COMMIT_MESSAGE =~ $TICKET ]]
    then
        echo "Ticket '${TICKET}', matched in current branch name, appended to commit message."

        if [[ $COMMIT_MESSAGE == "TEST"* ]] || [[ $COMMIT_MESSAGE == "test"* ]] || [[ $COMMIT_MESSAGE == "MAINT"* ]] || [[ $COMMIT_MESSAGE == "maint"* ]]
        then
            echo ${COMMIT_MESSAGE}" - "${TICKET} > $COMMIT_MSG_FILE
            echo "Ticket '${TICKET}', was appended to the commit message!......................"
            echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
        else
            echo "TEST: ${COMMIT_MESSAGE} - ${TICKET}" > $COMMIT_MSG_FILE
            echo "TEST: was pre-fixed to the commit message...................................."
            echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
        fi
    else
        if [[ $COMMIT_MESSAGE != "TEST"* ]] && [[ $COMMIT_MESSAGE != "test"* ]] && [[ $COMMIT_MESSAGE != "MAINT"* ]] && [[ $COMMIT_MESSAGE != "maint"* ]]
        then
            echo "TEST: ${COMMIT_MESSAGE}" > $COMMIT_MSG_FILE
            echo "TEST: was pre-fixed to the commit message...................................."
            echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
        fi
    fi

elif [[ $COMMIT_MESSAGE == "MAINT"* ]] || [[ $COMMIT_MESSAGE == "TEST"* ]] || [[ $COMMIT_MESSAGE == "test"* ]] || [[ $COMMIT_MESSAGE == "maint"* ]]
then
    echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
    exit 0;
else
    echo "TEST: "${COMMIT_MESSAGE} > $COMMIT_MSG_FILE
    echo "TEST: was pre-fixed to the commit message...................................."
    echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
fi