#!/bin/bash

#Prepends commit message with STRY, DEF, BAK tickets or MAINT

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
# echo "CURRENT_BRANCH = "${CURRENT_BRANCH}

separator=""
if [[ $CURRENT_BRANCH == *"_"* ]]
then
  #echo "branch name cotains underscore"
  separator="_"
elif [[ $CURRENT_BRANCH == *"-"* ]]
then
    #echo "branch name cotains hyphen"
    separator="-"
fi

arr=(${CURRENT_BRANCH//${separator}/ })
CURRENT_BRANCH=arr[0]

echo "CURRENT_BRANCH = "${CURRENT_BRANCH}

PREFIX_REGEX="((DEF|BAK|STRY|MAINT|def|bak|stry|maint)[0-9]*)(_*).*"
if [[ $CURRENT_BRANCH =~ $PREFIX_REGEX ]]
then
    TICKET="${BASH_REMATCH[0]}"
    COMMIT_MESSAGE=$(cat $COMMIT_MSG_FILE)
    
    if [[ $COMMIT_MESSAGE =~ 'TEST: '$TICKET ]]
    then
        exit 0;
    fi

    echo "Ticket '${TICKET}', matched in current branch name, prepended to commit message."
    echo "TEST: ${TICKET} - ${COMMIT_MESSAGE}" > $COMMIT_MSG_FILE
fi